[book]
title = "PostProject"
description = "User, integration, and contributor documentation for PostProject"
authors = ["PostProject contributors"]
language = "en"
src = "src"

[build]
build-dir = "../target/postproject"

[output.html]
git-repository-url = "https://github.com/eseifert/postproject"
site-url = "/postproject/"
